version: '3.8'

services:
  bank-account-kata:
    image: zmaazouz/bankaccount:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - bank-account-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev

networks:
  bank-account-network:
    driver: bridge
